name: Clean Workflows

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间的午夜执行
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Clean Up
      run: |
        # 设置要保留的工作流记录的最大天数
        RETENTION_DAYS=2

        # 计算截止日期，即保留的最大天数前的日期
        CUTOFF_DATE=$(date -I -d "$RETENTION_DAYS days ago")

        # 列出所有已完成的工作流运行记录
        RUNS=$(gh api "repos/$GITHUB_REPOSITORY/actions/runs?event=workflow_run")

        # 遍历运行记录并删除旧的运行记录
        for run in $(echo "$RUNS" | jq -r '.workflow_runs[] | select(.created_at < "'"$CUTOFF_DATE"'" and .status == "completed") | .id'); do
          echo "Deleting workflow run $run"
          gh api -X DELETE "repos/$GITHUB_REPOSITORY/actions/runs/$run"
        done
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
